### ISSUE TITLE
Hand Segmentation X-ray

### ISSUE THREAD

**Issue by ss8319** [aimi-bonn/hand-segmentation#1]
**Setup**
Python 3.10.13
Windows 
Utilising Microsoft Azure Compute- NVIDIA A100 GPU

**Torch Version**
```
torch                     2.0.1                    pypi_0    pypi
torchmetrics              0.7.0                    pypi_0    pypi
torchvision               0.16.1                   pypi_0    pypi
```

To create error:
1. Data organised into 
![image](https://github.com/aimi-bonn/hand-segmentation/assets/72968523/29a04e0b-d001-432c-ba14-f3274aa74dc8)
Files in .png.
2. python /home/azureuser/cloudfiles/code/Users/shamus/hand-segmentation/FSCNN/train_model.py --config /home/azureuser/cloudfiles/code/Users/shamus/hand-segmentation/FSCNN/configs/defaults.yml     --data.train_path=/home/azureuser/cloudfiles/code/Users/shamus/Data_Splits/train     --data.val_path=/home/azureuser/cloudfiles/code/Users/shamus/Data_Splits/val   

**Comments**
I am thinking the error comes from the data file organisation. Can you give some comments on how the data should be organised?

**Error**
```
(hand-seg) azureuser@bone-gpua100:~/cloudfiles/code$ python /home/azureuser/cloudfiles/code/Users/shamus/hand-segmentation/FSCNN/train_model.py --config /home/azureuser/cloudfiles/code/Users/shamus/hand-segmentation/FSCNN/configs/defaults.yml             --data.train_path=/home/azureuser/cloudfiles/code/Users/shamus/Data_Splits/train     --data.val_path=/home/azureuser/cloudfiles/code/Users/shamus/Data_Splits/val   
/anaconda/envs/hand-seg/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/anaconda/envs/hand-seg/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
05 Dec 23 09:32:40      INFO    seed.py Global seed set to 42
05 Dec 23 09:32:40      INFO    instantiator.py Created a temporary directory at /tmp/tmpudwxm5sf
05 Dec 23 09:32:40      INFO    instantiator.py Writing /tmp/tmpudwxm5sf/_remote_module_non_scriptable.py
05 Dec 23 09:32:40      INFO    datasets.py     before 0
05 Dec 23 09:32:40      INFO    datasets.py     after 0
05 Dec 23 09:32:40      INFO    rank_zero.py    Using 16bit native Automatic Mixed Precision (AMP)
05 Dec 23 09:32:41      INFO    rank_zero.py    GPU available: True, used: True
05 Dec 23 09:32:41      INFO    rank_zero.py    TPU available: False, using: 0 TPU cores
05 Dec 23 09:32:41      INFO    rank_zero.py    IPU available: False, using: 0 IPUs
05 Dec 23 09:32:41      INFO    rank_zero.py    HPU available: False, using: 0 HPUs
05 Dec 23 09:32:41      INFO    cli.py  Output directory set to output/debug/version_2
05 Dec 23 09:32:41      INFO    log.py  Logs saved to run.log
05 Dec 23 09:32:41      INFO    log.py  Core count             = 24
05 Dec 23 09:32:41      INFO    log.py  Python version         = 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
05 Dec 23 09:32:41      INFO    log.py  Pytorch version        = 2.0.1+cu117
05 Dec 23 09:32:41      INFO    log.py  Albumentations version = 1.1.0
05 Dec 23 09:32:41      INFO    log.py  CUDA version           = 11.7
05 Dec 23 09:32:41      INFO    log.py  CUDA count             = 1
05 Dec 23 09:32:41      INFO    log.py  CUDA name              = NVIDIA A100 80GB PCIe
05 Dec 23 09:32:41      INFO    train_model.py  ========== start training ==========
05 Dec 23 09:32:42      INFO    gpu.py  LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
05 Dec 23 09:32:42      INFO    model_summary.py
   | Name                             | Type                         | Params
-----------------------------------------------------------------------------------
0  | backbone                         | FastSurferCNN                | 447 K 
1  | backbone.encode1                 | CompetitiveEncoderBlockInput | 27.7 K
2  | backbone.encode1.conv0           | Conv2d                       | 832   
3  | backbone.encode1.conv1           | Conv2d                       | 25.6 K
4  | backbone.encode1.conv2           | Conv2d                       | 1.1 K 
5  | backbone.encode1.bn0             | BatchNorm2d                  | 2     
6  | backbone.encode1.bn1             | BatchNorm2d                  | 64    
7  | backbone.encode1.bn2             | BatchNorm2d                  | 64    
8  | backbone.encode1.bn3             | BatchNorm2d                  | 64    
9  | backbone.encode1.prelu           | PReLU                        | 1     
10 | backbone.encode1.maxpool         | MaxPool2d                    | 0     
11 | backbone.encode2                 | CompetitiveEncoderBlock      | 52.5 K
12 | backbone.encode2.conv0           | Conv2d                       | 25.6 K
13 | backbone.encode2.conv1           | Conv2d                       | 25.6 K
14 | backbone.encode2.conv2           | Conv2d                       | 1.1 K 
15 | backbone.encode2.bn1             | BatchNorm2d                  | 64    
16 | backbone.encode2.bn2             | BatchNorm2d                  | 64    
17 | backbone.encode2.bn3             | BatchNorm2d                  | 64    
18 | backbone.encode2.prelu           | PReLU                        | 1     
19 | backbone.encode2.maxpool         | MaxPool2d                    | 0     
20 | backbone.encode3                 | CompetitiveEncoderBlock      | 52.5 K
21 | backbone.encode3.conv0           | Conv2d                       | 25.6 K
22 | backbone.encode3.conv1           | Conv2d                       | 25.6 K
23 | backbone.encode3.conv2           | Conv2d                       | 1.1 K 
24 | backbone.encode3.bn1             | BatchNorm2d                  | 64    
25 | backbone.encode3.bn2             | BatchNorm2d                  | 64    
26 | backbone.encode3.bn3             | BatchNorm2d                  | 64    
27 | backbone.encode3.prelu           | PReLU                        | 1     
28 | backbone.encode3.maxpool         | MaxPool2d                    | 0     
29 | backbone.encode4                 | CompetitiveEncoderBlock      | 52.5 K
30 | backbone.encode4.conv0           | Conv2d                       | 25.6 K
31 | backbone.encode4.conv1           | Conv2d                       | 25.6 K
32 | backbone.encode4.conv2           | Conv2d                       | 1.1 K 
33 | backbone.encode4.bn1             | BatchNorm2d                  | 64    
34 | backbone.encode4.bn2             | BatchNorm2d                  | 64    
35 | backbone.encode4.bn3             | BatchNorm2d                  | 64    
36 | backbone.encode4.prelu           | PReLU                        | 1     
37 | backbone.encode4.maxpool         | MaxPool2d                    | 0     
38 | backbone.bottleneck              | CompetitiveDenseBlock        | 52.5 K
39 | backbone.bottleneck.conv0        | Conv2d                       | 25.6 K
40 | backbone.bottleneck.conv1        | Conv2d                       | 25.6 K
41 | backbone.bottleneck.conv2        | Conv2d                       | 1.1 K 
42 | backbone.bottleneck.bn1          | BatchNorm2d                  | 64    
43 | backbone.bottleneck.bn2          | BatchNorm2d                  | 64    
44 | backbone.bottleneck.bn3          | BatchNorm2d                  | 64    
45 | backbone.bottleneck.prelu        | PReLU                        | 1     
46 | backbone.decode4                 | CompetitiveDecoderBlock      | 52.5 K
47 | backbone.decode4.conv0           | Conv2d                       | 25.6 K
48 | backbone.decode4.conv1           | Conv2d                       | 25.6 K
49 | backbone.decode4.conv2           | Conv2d                       | 1.1 K 
50 | backbone.decode4.bn1             | BatchNorm2d                  | 64    
51 | backbone.decode4.bn2             | BatchNorm2d                  | 64    
52 | backbone.decode4.bn3             | BatchNorm2d                  | 64    
53 | backbone.decode4.prelu           | PReLU                        | 1     
54 | backbone.decode4.unpool          | MaxUnpool2d                  | 0     
55 | backbone.decode3                 | CompetitiveDecoderBlock      | 52.5 K
56 | backbone.decode3.conv0           | Conv2d                       | 25.6 K
57 | backbone.decode3.conv1           | Conv2d                       | 25.6 K
58 | backbone.decode3.conv2           | Conv2d                       | 1.1 K 
59 | backbone.decode3.bn1             | BatchNorm2d                  | 64    
60 | backbone.decode3.bn2             | BatchNorm2d                  | 64    
61 | backbone.decode3.bn3             | BatchNorm2d                  | 64    
62 | backbone.decode3.prelu           | PReLU                        | 1     
63 | backbone.decode3.unpool          | MaxUnpool2d                  | 0     
64 | backbone.decode2                 | CompetitiveDecoderBlock      | 52.5 K
65 | backbone.decode2.conv0           | Conv2d                       | 25.6 K
66 | backbone.decode2.conv1           | Conv2d                       | 25.6 K
67 | backbone.decode2.conv2           | Conv2d                       | 1.1 K 
68 | backbone.decode2.bn1             | BatchNorm2d                  | 64    
69 | backbone.decode2.bn2             | BatchNorm2d                  | 64    
70 | backbone.decode2.bn3             | BatchNorm2d                  | 64    
71 | backbone.decode2.prelu           | PReLU                        | 1     
72 | backbone.decode2.unpool          | MaxUnpool2d                  | 0     
73 | backbone.decode1                 | CompetitiveDecoderBlock      | 52.5 K
74 | backbone.decode1.conv0           | Conv2d                       | 25.6 K
75 | backbone.decode1.conv1           | Conv2d                       | 25.6 K
76 | backbone.decode1.conv2           | Conv2d                       | 1.1 K 
77 | backbone.decode1.bn1             | BatchNorm2d                  | 64    
78 | backbone.decode1.bn2             | BatchNorm2d                  | 64    
79 | backbone.decode1.bn3             | BatchNorm2d                  | 64    
80 | backbone.decode1.prelu           | PReLU                        | 1     
81 | backbone.decode1.unpool          | MaxUnpool2d                  | 0     
82 | backbone.classifier              | ClassifierBlock              | 66    
83 | backbone.classifier.conv         | Conv2d                       | 66    
84 | loss                             | CombinedLoss                 | 0     
85 | loss.cross_entropy_loss          | CrossEntropy                 | 0     
86 | loss.cross_entropy_loss.nll_loss | CrossEntropyLoss             | 0     
87 | loss.dice_loss                   | DiceLoss                     | 0     
-----------------------------------------------------------------------------------
447 K     Trainable params
0         Non-trainable params
447 K     Total params
0.896     Total estimated model params size (MB)
/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/loggers/tensorboard.py:250: UserWarning: Could not log computational graph since the `model.example_input_array` attribute is not set or `input_array` was not given
  rank_zero_warn(
Sanity Checking: 0it [00:00, ?it/s]/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:127: UserWarning: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.
  rank_zero_warn(
Traceback (most recent call last): 
  File "/home/azureuser/cloudfiles/code/Users/shamus/hand-segmentation/FSCNN/train_model.py", line 31, in <module>
    main()
  File "/home/azureuser/cloudfiles/code/Users/shamus/hand-segmentation/FSCNN/train_model.py", line 27, in main
    cli.trainer.fit(cli.model, cli.datamodule)
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 207, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1856, in reset_train_dataloader
    self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING, model=model)
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 459, in _request_dataloader
    dataloader = source.dataloader()
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 536, in dataloader
    return method()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/bone-gpua100/code/Users/shamus/hand-segmentation/FSCNN/lib/datasets.py", line 317, in train_dataloader
    return DataLoader(
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/anaconda/envs/hand-seg/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by sRassmann** [comment]
To reproduce our training from e.g. the `Tensormask` masks, you can set the `pretrain` flag in the dataset i.e. run with `python train_model.py [...] --dataset.pretrain True`. This calls the simplified [PretrainDataset](https://github.com/aimi-bonn/hand-segmentation/blob/5f042dea2cadeb6ab2068fbbe16429da63223fa7/FSCNN/lib/datasets.py#L198).

This statically calls to the paths:
``` python
mask_path="../../data/masks/tensormask/bone_age",
weight_path="../../data/masks/weights/",
``` 

So the match it, you'd either (1) need to put all input images in `../../data/masks/tensormask/bone_age` and masks (with the same name) into `../../data/masks/weights/`, (2) change the code statically, or (3) adapt the CLI to forward this.

I think I wanted to do (3), but it was never necessary so I just left it as is.
